In [9]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [10]:
#creating the dataframe and load it
df = pd.read_csv("homeprice.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
#data preprocessing
df.bedrooms.median()

4.0

In [12]:
#storing median value to the null position of bedrooms column
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
#creating model and training the dataset using fit method
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [14]:
import joblib
joblib.dump(model, 'model_homeprice.joblib')
mj = joblib.load('model_homeprice.joblib')

In [15]:
mj.predict([[3000,3,40]])

C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [33]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [34]:
model.intercept_

221323.00186540437

In [35]:
#predict the price
model.predict([[3000,3,40]])

C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [36]:
d = pd.read_csv("predict.csv")
d

area  bedrooms  age
0  3000         3   40
1  2500         4    5
2  1900         3   12

In [37]:
p = model.predict(d)

In [38]:
d['price'] = p
d

area  bedrooms  age          price
0  3000         3   40  498408.251580
1  2500         4    5  578876.037489
2  1900         3   12  465627.666886

In [40]:
d.to_csv("final_result.csv",index = False)

NameError: name 'model' is not defined